#!/bin/sh
path=$1
src=src/main/java/com/lg/$path
res=src/main/resources
build=build.gradle



if [ ! -d "$path" ]; then
 mkdir -p $path
 cd $path
 mkdir -p $src
 mkdir -p libs
 mkdir -p $res
 touch build.gradle
else
    echo $path exist
    exit 0
fi

cat > $build << EOF
apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

def name = '$1'
def ver = 'v1.0.0'

buildscript{
    repositories{
        jcenter()
    }
    dependencies{
        classpath 'com.github.jengelman.gradle.plugins:shadow:4.0.0'
    }
}


shadowJar{
    manifest{
        attributes 'Main-Class':'com.lg.$path.Main'
    }
    baseName = name
    classifier = null
    version = ver
    dependencies{

    }
}
repositories{
    jcenter()
    google()
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8


dependencies{
    implementation fileTree(dir:'libs',include: ['*.jar'])
}
EOF

cd $src
cat > Main.java << EOF
package com.lg.$path;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;

public class Main {

    public static Properties pop;
    public static  File popFile;

    public static void main(String[] args) {
        System.out.println("hello world");
    }

    public static String getRoot() {
        String currentPath = Main.class.getResource("").getPath();
        String parent = currentPath.substring(5, currentPath.length() - ${#path} - 12 - 2 - Main.class.getPackage().getName().length());
        return parent + "$path";
    }

     private static void createProperties() {
        popFile = new File(getRoot(), "config.properties");
        pop = new Properties();
        if (!popFile.exists()) {

             if(!popFile.getParentFile().exists()){
                popFile.getParentFile().mkdirs();
            }
            
            try {
                popFile.createNewFile();
                pop.setProperty("title", "hello world");
                pop.store(new FileWriter(popFile), "init");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        try {
            pop.load(new FileReader(popFile));        
            String title = pop.getProperty("title");
            System.out.println("pop  title : "+title);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
EOF

